steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-f"
      - "Dockerfile"
      - "-t"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/training:latest"
      - "."

images:
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/training:latest"

substitutions:
  _REGION: us-central1
  _REPO: training-images
